### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by OthmanAdi** [graiz/cbot#2]
**While running the code the i get the following error in the Terminal**

**Comment by gfish-git** [comment]
Fix in PR resolved this for me

**Comment by vas2201** [comment]
> Fix in PR resolved this for me

can you explain what id PR means ?, I am gettig the same error

**Comment by gfish-git** [comment]
See line 164 here https://github.com/graiz/cbot/pull/1/files. This change fixed issue for me.

**Comment by graiz** [comment]
Fixed with recent change.
